export const CATEGORIES = [
  { slug: "car-care", label: "Car Care" },
  { slug: "catering", label: "Catering" },
  { slug: "cycle-repair", label: "Cycle Repair" },
  { slug: "driver", label: "Driver" },
  { slug: "electrician", label: "Electrician" },
  { slug: "hospital", label: "Hospital" },
  { slug: "internet", label: "Internet" },
  { slug: "laundry", label: "Laundry" },
  { slug: "milk-vendor", label: "Milk Vendor" },
  { slug: "news-paper", label: "Newspaper" },
  { slug: "restaurant", label: "Restaurant" },
  { slug: "salon", label: "Salon" },
  { slug: "school", label: "School" },
  { slug: "supermarket", label: "Supermarket" },
];